networks:
  pi-net:
    external: true

services:
  les-bons-comptes:
    build: .
    image: les-bons-comptes:latest
    container_name: les-bons-comptes
    restart: unless-stopped
    networks:
      - pi-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.les-bons-comptes.rule=PathPrefix(`/les-bons-comptes`)"
      - "traefik.http.routers.les-bons-comptes.entrypoints=web"
      - "traefik.http.routers.les-bons-comptes.middlewares=les-bons-comptes-redirect,les-bons-comptes-strip"
      - "traefik.http.middlewares.les-bons-comptes-redirect.redirectregex.regex=^(.*)/les-bons-comptes$$"
      - "traefik.http.middlewares.les-bons-comptes-redirect.redirectregex.replacement=$${1}/les-bons-comptes/"
      - "traefik.http.middlewares.les-bons-comptes-redirect.redirectregex.permanent=true"
      - "traefik.http.middlewares.les-bons-comptes-strip.stripprefix.prefixes=/les-bons-comptes"
      - "traefik.http.services.les-bons-comptes.loadbalancer.server.port=80"
